easy-rent/config/routes.rb
Rails.application.routes.draw do
  resources :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

easy-rent/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

easy-rent/app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, presence: true
  validates :dob, presence: true
  validates :mobile_phone, presence: true
end

easy-rent/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

easy-rent/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :load_customer, only: %i[show edit update destroy]
  def index
    @customers = Customer.order(:name)
  end

  def show

  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new customer_params

    if @customer.save
      redirect_to customers_path, notice: "Cliente cadastrado com sucesso."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def  edit

  end

  def update
    if @customer.update customer_params
      redirect_to customer_params, notice: "Cliente atualizado com sucesso."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy

  end

  private

  def customer_params
    params.require(:customer).permit(:name, :dob, :mobile_phone, :email)
  end

  def load_customer
    @customer = Customer.find params[:id]
  end

end

easy-rent/app/helpers/application_helper.rb
module ApplicationHelper
end

easy-rent/app/helpers/customers_helper.rb
module CustomersHelper
end

easy-rent/app/views/customers/_customer.html.erb
<div class="card">
   <div class="card-body">
      <div class="d-flex">
          <spam class="flex-grow-1 fw-bold">Nome</spam>
          <spam> <%= customer.name %></spam>
       </div>
     </div>
  <div class="card-footer">
    <%= link_to "Editar", edit_customer_path(customer), class: "btn btn-info" %>
  </div>

</div>

easy-rent/app/views/customers/_form.html.erb
<div class="card">
  <%= simple_form_for @customer do |form| %>
   <div class="card-body">
     <div class="row">
        <div class="col-12 col-md-9">
          <%= form.input :name %>
        </div>
        <div class="col-12 col-md-3">
          <%= form.input :dob, html5: true %>
        </div>
      </div>
          <%= form.input :mobile_phone %>
          <%= form.input :email %>
    </div>
  <div class="card-footer d-flex justify-content-between ">
    <%= link_to "Voltar",  customers_path , class:"btn btn-secondary" %>
    <%= form.button :button, class: "btn-primary" %>
   </div>
  <% end %>

easy-rent/app/views/customers/edit.html.erb
<%= render "form" %>

easy-rent/app/views/customers/index.html.erb
<div class="d-flex">
  <h1 class="flex-grow-1"> Lista de Clientes</h1>
  <div class="list-actions">
    <%= link_to "Novo", new_customer_path, class: "btn btn-primary" %>
  </div>

</div>


<div class="d-flex flex-column gap-4">
<%= render @customers %>
</div>

easy-rent/app/views/customers/new.html.erb
<%= render "form" %>

easy-rent/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyRent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>